sayı_1 = float(input("Birinci sayıyı giriniz: "))
sayı_2 = float(input("İkinci sayıyı giriniz: "))
print(f"toplam = {sayı_1 + sayı_2}")
print(f"çarpım = {sayı_1 * sayı_2}")
print(f"fark = {sayı_1 - sayı_2}")
print(f"bölüm = {sayı_1 / sayı_2}")